name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'RELEASE')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r .version custom_components/ennatuurlijk_disruptions/manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create HACS-style zip archive
        run: |
          cd custom_components/ennatuurlijk_disruptions
          zip -r ../../ennatuurlijk_disruptions.zip .
          cd ../../

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: ennatuurlijk_disruptions.zip
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
